from __future__ import annotations

from enum import Enum
from typing import Final


BytesLike = bytes | bytearray | memoryview | str


class XprocError(RuntimeError):
    status: "Status"
    layout_error: "LayoutError"


class Status(Enum):
    OK = ...
    AGAIN = ...
    BUFFER_TOO_SMALL = ...
    INVALID_ARGUMENT = ...
    LOGIC_ERROR = ...
    LAYOUT_ERROR = ...
    RUNTIME_ERROR = ...
    NO_MEMORY = ...
    INTERNAL_ERROR = ...


class EndpointKind(Enum):
    PRODUCER = ...
    CONSUMER = ...
    OBSERVER = ...


class Backend(Enum):
    SHARED_MEMORY = ...
    SOCKET = ...


class ChannelType(Enum):
    FIXED = ...
    VARLEN = ...


class LayoutError(Enum):
    NONE = ...
    NOT_ATTACHED = ...
    BAD_MAGIC = ...
    NOT_READY_TIMEOUT = ...
    VERSION_MISMATCH = ...
    HEADER_SIZE_MISMATCH = ...
    LAYOUT_TYPE_MISMATCH = ...
    FIXED_ITEM_SIZE_MISMATCH = ...
    SCHEMA_ID_MISMATCH = ...
    ALIGNMENT_INVALID = ...
    CAPACITY_INSUFFICIENT = ...


class TransportOptions:
    backend: Backend
    path: str | None
    shm_size: int
    item_size: int
    data_align: int
    schema_id: int
    creator_timestamp_ns: int
    creator_flags: int
    create_if_missing: bool
    channel_type: ChannelType
    win32_object_namespace: str | None
    socket_host: str | None
    socket_port: int
    socket_listen: bool
    socket_connect_retries: int
    socket_connect_retry_ms: int

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...


class Snapshot:
    write_pos: int
    read_pos: int
    commit_seq: int
    read_wake_seq: int
    attach_count: int
    producer_pid: int

    def __repr__(self) -> str: ...


class Producer:
    def __init__(self, options: TransportOptions) -> None: ...
    def close(self) -> None: ...
    def options(self) -> TransportOptions: ...
    def send_fixed_bytes(self, value: BytesLike) -> None: ...
    def send_fixed_sized(self, value: BytesLike) -> None: ...
    def send_varlen(self, value: BytesLike) -> None: ...
    def socket_port(self) -> int: ...
    def __enter__(self) -> Producer: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...


class Consumer:
    def __init__(self, options: TransportOptions) -> None: ...
    def close(self) -> None: ...
    def options(self) -> TransportOptions: ...
    def pending_len(self) -> int: ...
    def poll_copy(self) -> bytes | None: ...
    def wait(self) -> None: ...
    def socket_port(self) -> int: ...
    def __enter__(self) -> Consumer: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...


class Observer:
    def __init__(self, options: TransportOptions) -> None: ...
    def close(self) -> None: ...
    def options(self) -> TransportOptions: ...
    def snapshot(self) -> Snapshot: ...
    def peek_copy(self) -> bytes | None: ...
    def __enter__(self) -> Observer: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...


INFER_EXISTING_SHM_SIZE: Final[int]
__version__: str


OK: Final[Status]
AGAIN: Final[Status]
BUFFER_TOO_SMALL: Final[Status]
INVALID_ARGUMENT: Final[Status]
LOGIC_ERROR: Final[Status]
LAYOUT_ERROR: Final[Status]
RUNTIME_ERROR: Final[Status]
NO_MEMORY: Final[Status]
INTERNAL_ERROR: Final[Status]

PRODUCER: Final[EndpointKind]
CONSUMER: Final[EndpointKind]
OBSERVER: Final[EndpointKind]

SHARED_MEMORY: Final[Backend]
SOCKET: Final[Backend]

FIXED: Final[ChannelType]
VARLEN: Final[ChannelType]

NONE: Final[LayoutError]
NOT_ATTACHED: Final[LayoutError]
BAD_MAGIC: Final[LayoutError]
NOT_READY_TIMEOUT: Final[LayoutError]
VERSION_MISMATCH: Final[LayoutError]
HEADER_SIZE_MISMATCH: Final[LayoutError]
LAYOUT_TYPE_MISMATCH: Final[LayoutError]
FIXED_ITEM_SIZE_MISMATCH: Final[LayoutError]
SCHEMA_ID_MISMATCH: Final[LayoutError]
ALIGNMENT_INVALID: Final[LayoutError]
CAPACITY_INSUFFICIENT: Final[LayoutError]


def shm_size_for_data_capacity(data_capacity: int) -> int: ...
def shm_data_capacity_for_size(shm_size: int) -> int: ...
def status_string(status: Status) -> str: ...
def layout_error_string(error: LayoutError) -> str: ...
def version_string() -> str: ...
def current_process_id() -> int: ...
def last_error_message() -> str: ...
def last_layout_error() -> LayoutError: ...
def validate_options_for(kind: EndpointKind, options: TransportOptions) -> None: ...
def shm_unlink(path: str) -> None: ...
